<%
'--------------------------------------------------------------------
' Microsoft ADO
'
' (c) 1996 Microsoft Corporation.  All Rights Reserved.
'
'
'
' ADO constants include file for VBScript
'
'--------------------------------------------------------------------

''''CDO CONST
Const cdoSendUsingMethod ="http://schemas.microsoft.com/cdo/configuration/sendusing"
Const cdoSMTPServerPort ="http://schemas.microsoft.com/cdo/configuration/smtpserverportcdoSendUsingPort"
Const cdoSMTPServer ="http://schemas.microsoft.com/cdo/configuration/smtpserver"
Const cdoSendUsingPort =2 
Const cdoSMTPConnectionTimeout =5
Const cdoSMTPAuthenticate ="http://schemas.microsoft.com/cdo/configuration/smtpauthenticate"
Const cdoURLProxyServer ="http://schemas.microsoft.com/cdo/configuration/urlproxyserver"
Const cdoURLProxyBypass ="http://schemas.microsoft.com/cdo/configuration/urlproxybypass"
Const cdoURLGetLatestVersion ="http://schemas.microsoft.com/cdo/configuration/urlgetlatestversion"
Const cdoSendUserName ="http://schemas.microsoft.com/cdo/configuration/sendusername"
Const cdoSendPassword ="http://schemas.microsoft.com/cdo/configuration/sendpassword"
''''''''''''''''''''
%>








